// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBll_vt0n_o-HFS3wiVuxbhcqrhSe2icXQ',
    appId: '1:503871729956:web:7a495bb7f55ee12ff5c3b1',
    messagingSenderId: '503871729956',
    projectId: 'tech-gadgets-268cd',
    authDomain: 'tech-gadgets-268cd.firebaseapp.com',
    storageBucket: 'tech-gadgets-268cd.appspot.com',
    measurementId: 'G-M95FCPE64Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQH8mut09SD-IEkjsTn6Ub7IHo0QhQqgo',
    appId: '1:503871729956:android:5df5ff8d8a585d01f5c3b1',
    messagingSenderId: '503871729956',
    projectId: 'tech-gadgets-268cd',
    storageBucket: 'tech-gadgets-268cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNLevqpZ4gkAsJPm1Lf9g3JwILZGw16o',
    appId: '1:503871729956:ios:3a091d27177ded44f5c3b1',
    messagingSenderId: '503871729956',
    projectId: 'tech-gadgets-268cd',
    storageBucket: 'tech-gadgets-268cd.appspot.com',
    iosBundleId: 'com.example.techgadgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNLevqpZ4gkAsJPm1Lf9g3JwILZGw16o',
    appId: '1:503871729956:ios:3a091d27177ded44f5c3b1',
    messagingSenderId: '503871729956',
    projectId: 'tech-gadgets-268cd',
    storageBucket: 'tech-gadgets-268cd.appspot.com',
    iosBundleId: 'com.example.techgadgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBll_vt0n_o-HFS3wiVuxbhcqrhSe2icXQ',
    appId: '1:503871729956:web:cb234617109dc4b5f5c3b1',
    messagingSenderId: '503871729956',
    projectId: 'tech-gadgets-268cd',
    authDomain: 'tech-gadgets-268cd.firebaseapp.com',
    storageBucket: 'tech-gadgets-268cd.appspot.com',
    measurementId: 'G-NTQYFP0N73',
  );
}
